/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AuthorityRegistry {
  export type IssuerStruct = {
    wallet: AddressLike;
    legalName: string;
    displayName: string;
    metadataURI: string;
    status: BigNumberish;
    createdAt: BigNumberish;
    approvedAt: BigNumberish;
    suspendedAt: BigNumberish;
    revokedAt: BigNumberish;
    approvedBy: AddressLike;
  };

  export type IssuerStructOutput = [
    wallet: string,
    legalName: string,
    displayName: string,
    metadataURI: string,
    status: bigint,
    createdAt: bigint,
    approvedAt: bigint,
    suspendedAt: bigint,
    revokedAt: bigint,
    approvedBy: string
  ] & {
    wallet: string;
    legalName: string;
    displayName: string;
    metadataURI: string;
    status: bigint;
    createdAt: bigint;
    approvedAt: bigint;
    suspendedAt: bigint;
    revokedAt: bigint;
    approvedBy: string;
  };
}

export interface AuthorityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ISSUER_MANAGER_ROLE"
      | "ROOT_AUTHORITY_ROLE"
      | "approveIssuer"
      | "getIssuer"
      | "getIssuerStatus"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isAuthorizedIssuer"
      | "pause"
      | "paused"
      | "registerIssuer"
      | "renounceRole"
      | "revokeIssuer"
      | "revokeRole"
      | "supportsInterface"
      | "suspendIssuer"
      | "unpause"
      | "updateIssuerMetadataURI"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IssuerApproved"
      | "IssuerMetadataUpdated"
      | "IssuerRegistered"
      | "IssuerRevoked"
      | "IssuerSuspended"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ISSUER_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROOT_AUTHORITY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuerStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerIssuer",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendIssuer",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateIssuerMetadataURI",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ISSUER_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROOT_AUTHORITY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIssuerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateIssuerMetadataURI",
    data: BytesLike
  ): Result;
}

export namespace IssuerApprovedEvent {
  export type InputTuple = [wallet: AddressLike, approvedBy: AddressLike];
  export type OutputTuple = [wallet: string, approvedBy: string];
  export interface OutputObject {
    wallet: string;
    approvedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerMetadataUpdatedEvent {
  export type InputTuple = [wallet: AddressLike, metadataURI: string];
  export type OutputTuple = [wallet: string, metadataURI: string];
  export interface OutputObject {
    wallet: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRegisteredEvent {
  export type InputTuple = [wallet: AddressLike, legalName: string];
  export type OutputTuple = [wallet: string, legalName: string];
  export interface OutputObject {
    wallet: string;
    legalName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevokedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    revokedBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [wallet: string, revokedBy: string, reason: string];
  export interface OutputObject {
    wallet: string;
    revokedBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerSuspendedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    suspendedBy: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    wallet: string,
    suspendedBy: string,
    reason: string
  ];
  export interface OutputObject {
    wallet: string;
    suspendedBy: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuthorityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AuthorityRegistry;
  waitForDeployment(): Promise<this>;

  interface: AuthorityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ISSUER_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  ROOT_AUTHORITY_ROLE: TypedContractMethod<[], [string], "view">;

  approveIssuer: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getIssuer: TypedContractMethod<
    [wallet: AddressLike],
    [AuthorityRegistry.IssuerStructOutput],
    "view"
  >;

  getIssuerStatus: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isAuthorizedIssuer: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerIssuer: TypedContractMethod<
    [
      wallet: AddressLike,
      legalName: string,
      displayName: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeIssuer: TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  suspendIssuer: TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateIssuerMetadataURI: TypedContractMethod<
    [wallet: AddressLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ISSUER_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROOT_AUTHORITY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveIssuer"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getIssuer"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [AuthorityRegistry.IssuerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIssuerStatus"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedIssuer"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerIssuer"
  ): TypedContractMethod<
    [
      wallet: AddressLike,
      legalName: string,
      displayName: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "suspendIssuer"
  ): TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateIssuerMetadataURI"
  ): TypedContractMethod<
    [wallet: AddressLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "IssuerApproved"
  ): TypedContractEvent<
    IssuerApprovedEvent.InputTuple,
    IssuerApprovedEvent.OutputTuple,
    IssuerApprovedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerMetadataUpdated"
  ): TypedContractEvent<
    IssuerMetadataUpdatedEvent.InputTuple,
    IssuerMetadataUpdatedEvent.OutputTuple,
    IssuerMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRegistered"
  ): TypedContractEvent<
    IssuerRegisteredEvent.InputTuple,
    IssuerRegisteredEvent.OutputTuple,
    IssuerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevoked"
  ): TypedContractEvent<
    IssuerRevokedEvent.InputTuple,
    IssuerRevokedEvent.OutputTuple,
    IssuerRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerSuspended"
  ): TypedContractEvent<
    IssuerSuspendedEvent.InputTuple,
    IssuerSuspendedEvent.OutputTuple,
    IssuerSuspendedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "IssuerApproved(address,address)": TypedContractEvent<
      IssuerApprovedEvent.InputTuple,
      IssuerApprovedEvent.OutputTuple,
      IssuerApprovedEvent.OutputObject
    >;
    IssuerApproved: TypedContractEvent<
      IssuerApprovedEvent.InputTuple,
      IssuerApprovedEvent.OutputTuple,
      IssuerApprovedEvent.OutputObject
    >;

    "IssuerMetadataUpdated(address,string)": TypedContractEvent<
      IssuerMetadataUpdatedEvent.InputTuple,
      IssuerMetadataUpdatedEvent.OutputTuple,
      IssuerMetadataUpdatedEvent.OutputObject
    >;
    IssuerMetadataUpdated: TypedContractEvent<
      IssuerMetadataUpdatedEvent.InputTuple,
      IssuerMetadataUpdatedEvent.OutputTuple,
      IssuerMetadataUpdatedEvent.OutputObject
    >;

    "IssuerRegistered(address,string)": TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;
    IssuerRegistered: TypedContractEvent<
      IssuerRegisteredEvent.InputTuple,
      IssuerRegisteredEvent.OutputTuple,
      IssuerRegisteredEvent.OutputObject
    >;

    "IssuerRevoked(address,address,string)": TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
    IssuerRevoked: TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;

    "IssuerSuspended(address,address,string)": TypedContractEvent<
      IssuerSuspendedEvent.InputTuple,
      IssuerSuspendedEvent.OutputTuple,
      IssuerSuspendedEvent.OutputObject
    >;
    IssuerSuspended: TypedContractEvent<
      IssuerSuspendedEvent.InputTuple,
      IssuerSuspendedEvent.OutputTuple,
      IssuerSuspendedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
