/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { AuthorityRegistry } from "./AuthorityRegistry";
export type { ThincrsCertificateSBT } from "./ThincrsCertificateSBT";
