/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAuthorityRegistry {
  export type IssuerStruct = {
    wallet: AddressLike;
    legalName: string;
    displayName: string;
    metadataURI: string;
    status: BigNumberish;
    createdAt: BigNumberish;
    approvedAt: BigNumberish;
    suspendedAt: BigNumberish;
    revokedAt: BigNumberish;
    approvedBy: AddressLike;
  };

  export type IssuerStructOutput = [
    wallet: string,
    legalName: string,
    displayName: string,
    metadataURI: string,
    status: bigint,
    createdAt: bigint,
    approvedAt: bigint,
    suspendedAt: bigint,
    revokedAt: bigint,
    approvedBy: string
  ] & {
    wallet: string;
    legalName: string;
    displayName: string;
    metadataURI: string;
    status: bigint;
    createdAt: bigint;
    approvedAt: bigint;
    suspendedAt: bigint;
    revokedAt: bigint;
    approvedBy: string;
  };
}

export interface IAuthorityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ROOT_AUTHORITY_ROLE"
      | "getIssuer"
      | "getIssuerStatus"
      | "hasRole"
      | "isAuthorizedIssuer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ROOT_AUTHORITY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuerStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedIssuer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ROOT_AUTHORITY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIssuerStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedIssuer",
    data: BytesLike
  ): Result;
}

export interface IAuthorityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAuthorityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAuthorityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ROOT_AUTHORITY_ROLE: TypedContractMethod<[], [string], "view">;

  getIssuer: TypedContractMethod<
    [wallet: AddressLike],
    [IAuthorityRegistry.IssuerStructOutput],
    "view"
  >;

  getIssuerStatus: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isAuthorizedIssuer: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ROOT_AUTHORITY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIssuer"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [IAuthorityRegistry.IssuerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIssuerStatus"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedIssuer"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;

  filters: {};
}
