/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuthorityRegistry,
  IAuthorityRegistryInterface,
} from "../../../contracts/interfaces/IAuthorityRegistry";

const _abi = [
  {
    inputs: [],
    name: "ROOT_AUTHORITY_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "getIssuer",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "wallet",
            type: "address",
          },
          {
            internalType: "string",
            name: "legalName",
            type: "string",
          },
          {
            internalType: "string",
            name: "displayName",
            type: "string",
          },
          {
            internalType: "string",
            name: "metadataURI",
            type: "string",
          },
          {
            internalType: "enum IAuthorityRegistry.IssuerStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "uint64",
            name: "createdAt",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "approvedAt",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "suspendedAt",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "revokedAt",
            type: "uint64",
          },
          {
            internalType: "address",
            name: "approvedBy",
            type: "address",
          },
        ],
        internalType: "struct IAuthorityRegistry.Issuer",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "getIssuerStatus",
    outputs: [
      {
        internalType: "enum IAuthorityRegistry.IssuerStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "isAuthorizedIssuer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAuthorityRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthorityRegistryInterface {
    return new Interface(_abi) as IAuthorityRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAuthorityRegistry {
    return new Contract(address, _abi, runner) as unknown as IAuthorityRegistry;
  }
}
